### ISSUE TITLE
fails to compile in visual studio 2017

### ISSUE THREAD

**Issue by cppdev-123** [ShiftMediaProject/libcdio#1]
I launch the libcdio.sln file in visual studio 2017 which converts it to a newer solution
but the generated one is completely broken
the files need to be copied to other directories
some files are missing
some other problems

I want to compile with /MT flag because my project uses it

**Comment by Sibras** [comment]
The project shouldnt need to be converted as it has 2017 support built in and should just natively open.
As you can see form the releases [page ](https://github.com/ShiftMediaProject/libcdio/releases/tag/release-2.1.0-1) the CI system builds Visual Studio 2013, 2015, 2017 and 2019 using the provided project without any issues.

I would suggest double checking that you have a clean copy of the latest version and that you open the provided solution using the supplied batch file (libcdio_deps_with_latest_sdk.bat) which is used to correctly detect available windows sdk versions.

**Comment by cppdev-123** [comment]
where is this batch file ? I can't find it in the repo

**Comment by cppdev-123** [comment]
I was trying the one in MSVC dir but I found that there is another one in SMP dir but now it needs iconv library 
I'm going to install it and try

**Comment by Sibras** [comment]
The projects provided by this repo are the ones in SMP. Any other build projects are not supported by this repo. In order to use it correctly make sure you read the readme for explanation for how to get dependencies and build.
