### ISSUE TITLE
Can we get utility programs as well ?

### ISSUE THREAD

**Issue by aybe** [ShiftMediaProject/libcdio#2]
## Context

The repository is lacking [utility programs](https://www.gnu.org/software/libcdio/):

- cd-info
- cd-drive
- cd-paranoia
- cd-read
- cdda-player
- iso-info
- iso-read
- mmc-tool

## Your Environment

* Version Used: release-2.1.0-1
* Operating System and Version: Windows 10 1909
* Compiler and Version(s): Microsoft Visual Studio Enterprise 2019 Version 16.4.4

Thank you

Best regards

**Comment by Sibras** [comment]
This project is purely based on supporting the library for use use in other projects. There is currently not any plans to support the tools. Such work can be sponsored but without that it is unlikely that the tools will ever be supported.

**Comment by aybe** [comment]
Alright, thank you.
